### PR TITLE
fix: footer issues

### PR DESCRIPTION
**Pull request by lirena00**
changed the styling of footer from absolute to fixed and added background color to it which is matching with header and also added all the form on index page into a div container while adding a bottom padding of 50px to it so that it looks good 
image

### CODE REVIEW

**Comment by LiReNa00** [comment]
also I had a question 
um is tailwind not allowed or you haven't just used it?
also it would be cool to add a better player than the default one, I am referring to https://www.vidstack.io/ 
I can probably open a pr for that too that is if you allow

**Comment by unknownsrc** [comment]
Hell yeah. Thank you.

**Comment by unknownsrc** [comment]
> um is tailwind not allowed or you haven't just used it?

The last time I tried to move everything to it, it fucked up most of my CSS and I just gave up. 

> also it would be cool to add a better player than the default one, I am referring to https://www.vidstack.io/

It looks pretty Javascript-heavy to me. I'd rather keep it to stuff even the most schizophrenic of Tor users can render.

**Comment by lirena00** [comment]
> The last time I tried to move everything to it, it fucked up most of my CSS and I just gave up.
Oh I see 
 
> It looks pretty Javascript-heavy to me. I'd rather keep it to stuff even the most schizophrenic of Tor users can render.
fair enough ig but thanks for making presevertube 😉

**Pull request merged**
